# Feature Engineering:
## - We are creating new feature from existing features
# Fundamental rule  (very very imp)
## - ML Alg works with only numbers but not string data
## - If we are having string Data then we need to convert into numbers by using Feature Engineering 
- for that
## - Let us apply feature engineering 
## - convert string data into numberical data 

# 1 Feature Engineering 
- Pre - requistie is  python & Pandas
1. Function
2. Class
3. object 
4. method
5. keyword - args
  

## 1 Feature Scaling  (imp )
- Feature Scaling is a teachnique to standardize the indepentdent feature present the data in a fixed range
- It is preformed during the data pre-processing

## 2 Data pre-procossing 
- In machine learning data pre-processing is an important step
- The purpose of the techique is cleaning and organzing the raw data to make is suitsble for building and training machine learning models

## 3 Why Data Pre-processing in machine learning 
- Typically real-world data is incomplete inconsistent , inaccurate (contains errors or outliers) and often lacks specific attribute values/trends
- This is where data pre-processing enters the scenario -  helps to clean, format and organize the raw data thereby making it ready to use the data for machine learing models

## 4 what type of data we need to handle 
- Two type of data we need to handle
1. Numerical data
2. Categorical data

## 5 Numerical data
- Quantitative data is the maasurement of something monthly sales, or student scores etc.
- The natural way to represent these quantites is numerically (e.g 29 students  234689 in sales)
- So we need to understand how to transforming raw numberical data into features then we need to use this feature during machine learning

## 6 To handle Numerical data 
- Technique and purpose
- label encoder => To convert all character / categorical variable to be numberic
- stadardScaler => To Transfrom a feature which is mean to 0 and standard deviation to 1
- Transforming Features => We can tranform features
- Handling outlier => To handle outlier
- Impute missing Values => To impute missing value with strategy

## 7 To handle categorical data
- Technique and purpose
- Encodeing norminal categories => To do one hot encoding
- Encodeing ordinal categoriess => Ordinal categorical
- Imputing categorical missing values => Imputing categorical missing values with most frequentstrategy

## 8 scikit-learn installation 
- To execute all these example we need to install scikit-learn library

In [1]:
pip install scikit-learn


Note: you may need to restart the kernel to use updated packages.


## 9 lable Encoder
- By using this we can convert all character / categorical variable to be numeric

## 9.1 LableEncode class
- lableEncoder is predefined class in sklearn.preprocessing package
- We need to import this class from sklean.preprocessing pakage
- Once we imported then we need to create an object o lableEncoder class

## 9.2 fit_tranform(p) method
- fit_transform(p) is predefined method in LabelEncoder class
- We should access this method by using LabelEncoder object only
- This method converts categorical variable into numberical values

In [1]:
from sklearn.preprocessing import LabelEncoder
import pandas as pd

d={
    "Compay":["Google","Twitter","Google","Linkdin"],
    "Role":["Data science","Sales manager","HR","HR"]
}

df=pd.DataFrame(d)

print(df)

label_encoder=LabelEncoder()

df["Compay_n"]=label_encoder.fit_transform(df["Compay"])
df["Role_n"]=label_encoder.fit_transform(df["Role"])

print()
print(df)


    Compay           Role
0   Google   Data science
1  Twitter  Sales manager
2   Google             HR
3  Linkdin             HR

    Compay           Role  Compay_n  Role_n
0   Google   Data science         0       0
1  Twitter  Sales manager         2       2
2   Google             HR         0       1
3  Linkdin             HR         1       1


In [8]:
pip install sklearn

  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [15 lines of output]
      The 'sklearn' PyPI package is deprecated, use 'scikit-learn'
      rather than 'sklearn' for pip commands.
      
      Here is how to fix this error in the main use cases:
      - use 'pip install scikit-learn' rather than 'pip install sklearn'
      - replace 'sklearn' by 'scikit-learn' in your pip requirements files
        (requirements.txt, setup.py, setup.cfg, Pipfile, etc ...)
      - if the 'sklearn' package is used by one of your dependencies,
        it would be great if you take some time to track which package uses
        'sklearn' instead of 'scikit-learn' and report it to their issue tracker
      - as a last resort, set the environment variable
        SKLEARN_ALLOW_DEPRECATED_SKLEARN_PACKAGE_INSTALL=True to avoid this error
      
      More information is available at
      https://g

## 10 MinMaxScaler
- Min - max scaling is a common feature pre-processing technique which reults in scaled data values that fall in the range 0 to 1
1. 0 is minimum value
2. 1 is maximum value
- If we rescale the value of numeric feature then it is between two values

In [2]:
import pandas as pd
d={
    "x":[10,20,30,40,50],
    "Y":[25,50,75,100,125]
}

df=pd.DataFrame(d)

print(df)

    x    Y
0  10   25
1  20   50
2  30   75
3  40  100
4  50  125


In [12]:
# MinMaxScaler: single column

from sklearn.preprocessing import MinMaxScaler
import pandas as pd

d={
    "X":[10,20,30,40,50],
    "Y":[25,50,75,100,125]
}

df=pd.DataFrame(d)
mm_scale = MinMaxScaler(feature_range=(0,1))

print(df)

one_col = mm_scale.fit_transform(df[["X"]])
print()
print(one_col)

    X    Y
0  10   25
1  20   50
2  30   75
3  40  100
4  50  125

[[0.  ]
 [0.25]
 [0.5 ]
 [0.75]
 [1.  ]]


In [17]:
# MinMaxScaler: double column

from sklearn.preprocessing import MinMaxScaler
import pandas as pd

d={
    "X":[10,20,30,40,50],
    "Y":[25,50,75,100,125]
}

df=pd.DataFrame(d)
mm_scale = MinMaxScaler(feature_range=(0,1))

print(df)

one_col = mm_scale.fit_transform(df[["X"]])
two_col= mm_scale.fit_transform(df[["Y"]])
print()
print(one_col)
print()
print(two_col)

    X    Y
0  10   25
1  20   50
2  30   75
3  40  100
4  50  125

[[0.  ]
 [0.25]
 [0.5 ]
 [0.75]
 [1.  ]]

[[0.  ]
 [0.25]
 [0.5 ]
 [0.75]
 [1.  ]]


In [21]:
#MinMaxSclar : two coloumns

import pandas as pd 
from sklearn.preprocessing import MinMaxScaler

d={
    "X":[10,20,30,40,50],
    "Y":[25,50,75,100,125]
}

df=pd.DataFrame(d)
mm_sclar=MinMaxScaler(feature_range=(0,1))

print(df)

df[["X","Y"]]=mm_sclar.fit_transform(df[["X","Y"]])
print()
print(df)

    X    Y
0  10   25
1  20   50
2  30   75
3  40  100
4  50  125

      X     Y
0  0.00  0.00
1  0.25  0.25
2  0.50  0.50
3  0.75  0.75
4  1.00  1.00


## Classes
1. LabelEncoder  => fit_transorm()
2. MinMaxscaler  => fit_transorm()

## 11 Transforming Features
- By using Function Tranformer we can Tranform the features


In [26]:
# Function Tranformer

import numpy as np 
from sklearn.preprocessing import FunctionTransformer

a=[[10,20],[30,40],[50,60]]
f=np.array(a)
print(f)

def add_ten(x):
    return x + 10
    
obj=FunctionTransformer(add_ten)
result=obj.transform(f)

print()
print(result)

[[10 20]
 [30 40]
 [50 60]]

[[20 30]
 [40 50]
 [60 70]]


## Handling outlier (very very imp )
- Outlier => The value which is very faar from common data it can be small value and large value  eg 10,20,30,40,50 ,100
- Outlier means a large value compare with other values
- Some values are also out of the range of the feature so they are also considered as outliers
- Outlier affect our model's efficieny because it influence the model very much
  - Three way to handle these
1. Drop outlier of filter outlier
2. Making them using boolean condition
3. Transform into feature

In [33]:
# A Dataframe with outliers

import pandas as pd
import numpy as np

house=pd.DataFrame()

house['price']=[152331,673888,749990,199034]
house['room']=[2,3,2,116]
house['square_feet']=[1500,2500,1500,480000]

print(house)

    price  room  square_feet
0  152331     2         1500
1  673888     3         2500
2  749990     2         1500
3  199034   116       480000


In [36]:
# 1. drop outlier of filter outlier
import pandas as pd
import numpy as np

house=pd.DataFrame()

house['price']=[152331,673888,749990,199034]
house['room']=[2,3,2,116]
house['square_feet']=[1500,2500,1500,480000]

con1=house['room']<5
new=house[con1]

print(new)

    price  room  square_feet
0  152331     2         1500
1  673888     3         2500
2  749990     2         1500


In [39]:
# 2 Mark them as outliers

import pandas as pd
import numpy as np 

house=pd.DataFrame()

house['price']=[152331,673888,749990,199034]
house['room']=[2,3,2,116]
house['square_feet']=[1500,2500,1500,480000]

house["outlier"]=np.where(house['room']<5,0,1)

print(house)

    price  room  square_feet  outlier
0  152331     2         1500        0
1  673888     3         2500        0
2  749990     2         1500        0
3  199034   116       480000        1


## 13 Impute / handing Missing values
- We can impute missing values with different strategy
- These are two types of missing values
  1. Numeric missing values
  2. Categorical missing values

# 13 impute / handing missing values

check the missing values
- by using pandas
1. df.isna().sum
2. df.dropna(p)
3. df.fillna(p)
4. df.replace(p)

# check the missing values by using feature engineering
## 14 Impute missing numberic values
- Missing numberic values we can impute with different strategy
  1. mean
  2. median
  3. most_frequent
  4. constant

In [42]:
# Creating a Dataframe
import pandas as pd
import numpy as np

students=[
    [85,'M','verygood'],
    [95,'F','excellent'],
    [60,None,'good'],
    [None,'M','average'],
    [70,'M','good'],
    [None,None,'verygood'],
    [60,'F','verygood'],
    [98,'M','excellent']
]

cols=['marks','gender','result']
df=pd.DataFrame(students , columns=cols)

print(df)

   marks gender     result
0   85.0      M   verygood
1   95.0      F  excellent
2   60.0   None       good
3    NaN      M    average
4   70.0      M       good
5    NaN   None   verygood
6   60.0      F   verygood
7   98.0      M  excellent


In [48]:
# Imputing missing numeric values with mean strategy

import pandas as pd
import numpy as np
from sklearn.impute import SimpleImputer

students=[
    [85,'M','verygood'],
    [95,'F','excellent'],
    [60,None,'good'],
    [None,'M','average'],
    [70,'M','good'],
    [None,None,'verygood'],
    [60,'F','verygood'],
    [98,'M','excellent']
]

cols=['marks','gender','result']
df=pd.DataFrame(students , columns=cols)

print(df)

impute=SimpleImputer(
    missing_values=np.nan,
    strategy='mean'
)

result=df['marks'].values.reshape(-1,1)

df['marks']=impute.fit_transform(result)

print()
print(df)

   marks gender     result
0   85.0      M   verygood
1   95.0      F  excellent
2   60.0   None       good
3    NaN      M    average
4   70.0      M       good
5    NaN   None   verygood
6   60.0      F   verygood
7   98.0      M  excellent

   marks gender     result
0   85.0      M   verygood
1   95.0      F  excellent
2   60.0   None       good
3   78.0      M    average
4   70.0      M       good
5   78.0   None   verygood
6   60.0      F   verygood
7   98.0      M  excellent


In [47]:
print(df['marks'])
print()
print(df['marks'].values)
print()
print(df['marks'].values.reshape(-1,1))

0    85.0
1    95.0
2    60.0
3     NaN
4    70.0
5     NaN
6    60.0
7    98.0
Name: marks, dtype: float64

[85. 95. 60. nan 70. nan 60. 98.]

[[85.]
 [95.]
 [60.]
 [nan]
 [70.]
 [nan]
 [60.]
 [98.]]


In [1]:
# Imputing missing numeric values with median strategy

import pandas as pd
import numpy as np
from sklearn.impute import SimpleImputer

students=[
    [85,'M','verygood'],
    [95,'F','excellent'],
    [60,None,'good'],
    [None,'M','average'],
    [70,'M','good'],
    [None,None,'verygood'],
    [60,'F','verygood'],
    [98,'M','excellent']
]

cols=['marks','gender','result']
df=pd.DataFrame(students , columns=cols)

print(df)

impute=SimpleImputer(
    missing_values=np.nan,
    strategy='median'
)

result=df['marks'].values.reshape(-1,1)

df['marks']=impute.fit_transform(result)

print()
print(df)

   marks gender     result
0   85.0      M   verygood
1   95.0      F  excellent
2   60.0   None       good
3    NaN      M    average
4   70.0      M       good
5    NaN   None   verygood
6   60.0      F   verygood
7   98.0      M  excellent

   marks gender     result
0   85.0      M   verygood
1   95.0      F  excellent
2   60.0   None       good
3   77.5      M    average
4   70.0      M       good
5   77.5   None   verygood
6   60.0      F   verygood
7   98.0      M  excellent


In [2]:
# Imputing missing numeric values with most_frequent strategy

import pandas as pd
import numpy as np
from sklearn.impute import SimpleImputer

students=[
    [85,'M','verygood'],
    [95,'F','excellent'],
    [60,None,'good'],
    [None,'M','average'],
    [70,'M','good'],
    [None,None,'verygood'],
    [60,'F','verygood'],
    [98,'M','excellent']
]

cols=['marks','gender','result']
df=pd.DataFrame(students , columns=cols)

print(df)

impute=SimpleImputer(
    missing_values=np.nan,
    strategy='most_frequent'
)

result=df['marks'].values.reshape(-1,1)

df['marks']=impute.fit_transform(result)

print()
print(df)

   marks gender     result
0   85.0      M   verygood
1   95.0      F  excellent
2   60.0   None       good
3    NaN      M    average
4   70.0      M       good
5    NaN   None   verygood
6   60.0      F   verygood
7   98.0      M  excellent

   marks gender     result
0   85.0      M   verygood
1   95.0      F  excellent
2   60.0   None       good
3   60.0      M    average
4   70.0      M       good
5   60.0   None   verygood
6   60.0      F   verygood
7   98.0      M  excellent


In [10]:
# Imputing missing numeric values with constant strategy

import pandas as pd
import numpy as np
from sklearn.impute import SimpleImputer

students=[
    [85,'M','verygood'],
    [95,'F','excellent'],
    [60,None,'good'],
    [None,'M','average'],
    [70,'M','good'],
    [None,None,'verygood'],
    [60,'F','verygood'],
    [98,'M','excellent']
]

cols=['marks','gender','result']
df=pd.DataFrame(students , columns=cols)

print(df)

impute=SimpleImputer(
    missing_values=np.nan,
    strategy='constant',

)

result=df['marks'].values.reshape(-1,1)

df['marks']=impute.fit_transform(result)

print()
print(df)

   marks gender     result
0   85.0      M   verygood
1   95.0      F  excellent
2   60.0   None       good
3    NaN      M    average
4   70.0      M       good
5    NaN   None   verygood
6   60.0      F   verygood
7   98.0      M  excellent

   marks gender     result
0   85.0      M   verygood
1   95.0      F  excellent
2   60.0   None       good
3    0.0      M    average
4   70.0      M       good
5    0.0   None   verygood
6   60.0      F   verygood
7   98.0      M  excellent


In [11]:
# Imputing missing numeric values with constant strategy but fill value with 80

import pandas as pd
import numpy as np
from sklearn.impute import SimpleImputer

students=[
    [85,'M','verygood'],
    [95,'F','excellent'],
    [60,None,'good'],
    [None,'M','average'],
    [70,'M','good'],
    [None,None,'verygood'],
    [60,'F','verygood'],
    [98,'M','excellent']
]

cols=['marks','gender','result']
df=pd.DataFrame(students , columns=cols)

print(df)

impute=SimpleImputer(
    missing_values=np.nan,
    strategy='constant',
    fill_value=80
)

result=df['marks'].values.reshape(-1,1)

df['marks']=impute.fit_transform(result)

print()
print(df)

   marks gender     result
0   85.0      M   verygood
1   95.0      F  excellent
2   60.0   None       good
3    NaN      M    average
4   70.0      M       good
5    NaN   None   verygood
6   60.0      F   verygood
7   98.0      M  excellent

   marks gender     result
0   85.0      M   verygood
1   95.0      F  excellent
2   60.0   None       good
3   80.0      M    average
4   70.0      M       good
5   80.0   None   verygood
6   60.0      F   verygood
7   98.0      M  excellent


# => According to the syntax Simplelmpute object will work with only SINGAL COLUMN ARRAY but not with other data 

In [7]:
print()
print(df)
print()
print(df['marks'])
print()
print(df['marks'].values)
print()
print(df['marks'].values.reshape(-1,1))


   marks gender     result
0   85.0      M   verygood
1   95.0      F  excellent
2   60.0   None       good
3    0.0      M    average
4   70.0      M       good
5    0.0   None   verygood
6   60.0      F   verygood
7   98.0      M  excellent

0    85.0
1    95.0
2    60.0
3     0.0
4    70.0
5     0.0
6    60.0
7    98.0
Name: marks, dtype: float64

[85. 95. 60.  0. 70.  0. 60. 98.]

[[85.]
 [95.]
 [60.]
 [ 0.]
 [70.]
 [ 0.]
 [60.]
 [98.]]
