# 1 Handling Categorical Data
### Categorical Data
- Categorical data are variables that contain label values rather than number values

### Types of Categorical data
- Nominal variable
- Ordinal variable

## Nomial Variable
- The variables which are having no-order those are called as Nominal variable
- Examples:
  1. pet variables values : cat,dog
  2. color variables values : blue, green , red

## Ordinal Variable
- The variable which are having an order those are called ordinal Variable
- Examples:
  1. Score variable values : low,medium,high
 
### Kind note 
- In real time mostly we do have nominal variable scenarios
- So please understand the below scenarios

# 2 Encoding Categorical Data
- There are 3 ways to convert categorical variable to numerical values
  1. Ordinal encoding
  2. One hot encoding
  3. Dummy variable encoding

## 2.1 Ordinal encoding 
- In ordinal encoding every nominal value is assigned an integer value
- Example
  1. blue : 0
  2. green : 1
  3. red : 2

In [2]:
# Ordinal encoding

from numpy import asarray
from sklearn.preprocessing import OrdinalEncoder

a=[['blue'],['green'],['red']]


data=asarray(a)

print(data)

[['blue']
 ['green']
 ['red']]


In [4]:
# Ordinal encoding

from numpy import asarray
from sklearn.preprocessing import OrdinalEncoder

data=asarray([['blue'],['green'],['red']])

print(data)

encoder=OrdinalEncoder()
result=encoder.fit_transform(data)

print()
print(result)

[['blue']
 ['green']
 ['red']]

[[0.]
 [1.]
 [2.]]


In [5]:
# Ordinal encoding

from numpy import asarray
from sklearn.preprocessing import OrdinalEncoder

data=asarray([['blue'],['green'],['red'],['orange']])

print(data)

encoder=OrdinalEncoder()
result=encoder.fit_transform(data)  # result=encoder.fit_transform(single column array be have to provide) 

print()
print(result)

[['blue']
 ['green']
 ['red']
 ['orange']]

[[0.]
 [1.]
 [3.]
 [2.]]


### Problem with ordinal encoding 
- If we have applied ordinal encoding on nominal values then it will be an order and having relationship but actually there is no relationship in between the norminal variables
- Machine learning algorithm understands like there is an order in between norminal values
- So it causes a problem like machine learning algorithm will produce poor performance
- We can solve this problem by using one hot encoding 

## 2.2 One hot encoding
- One-hot encoding allows us to turn nominal categoricaldata into feature with numberical values, while not mathenatically implly any ordinal relationship between thr classes.
- For nominal values integer encoding may not be enough and even it is misleading the model.
- Here one hot encoding helps it is technique where each of the nominal variables will be represented with binary values.

In [14]:
# One hot encoding 

from numpy import asarray
from sklearn.preprocessing import OneHotEncoder

a=[['apply'],['pear'],['apply'],['pear'],['apply']]
data=asarray(a)

print(data)

encoder=OneHotEncoder(sparse_output=False)
onehot=encoder.fit_transform(data)


print()
print(onehot)

[['apply']
 ['pear']
 ['apply']
 ['pear']
 ['apply']]

[[1. 0.]
 [0. 1.]
 [1. 0.]
 [0. 1.]
 [1. 0.]]


In [16]:
# One hot encoding 

from numpy import asarray
from sklearn.preprocessing import OneHotEncoder

a=[['blue'],['green'],['red']]
data=asarray(a)

print(data)

encoder=OneHotEncoder(
    sparse_output=False
)
onehot=encoder.fit_transform(data)


print()
print(onehot)

[['blue']
 ['green']
 ['red']]

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


## Dummy variable encoding  (very imp for interview)
- The one hot encoding create one binary variable for each category
- The problem  is that this representation includes redundancy
- For example if we know that [1,0,0] represents for first value and [0,1,0] reprsents for second value then we donot need another binary variable to represent third value , instead we could use ) values alone like [0,0]

- One hot encoding example
- Example
  1. blue:  1 0 0
  2. green: 0 1 0
  3. red  : 0 0 1

- Dummy variable encoding example
- Example
  1. blue: 0 0
  2. Green : 1 0
  3. Red : 0 1

### Conclusion
- If we drop first column from the result of one hot encoding then we will get dummy variable encoding 


In [19]:
# Dummy variable encoding  using drop first
from numpy import asarray
from sklearn.preprocessing import OneHotEncoder

a=[['blue'],['green'],['red']]
data=asarray(a)

print(data)

encoder=OneHotEncoder(
    drop='first',
    sparse_output=False
)
onehot=encoder.fit_transform(data)
print()
print(onehot)

[['blue']
 ['green']
 ['red']]

[[0. 0.]
 [1. 0.]
 [0. 1.]]


In [21]:
# Dummy variable encoding using drop if_binary
from numpy import asarray
from sklearn.preprocessing import OneHotEncoder

a=[['blue'],['green'],['red']]
data=asarray(a)

print(data)

encoder=OneHotEncoder(
    drop='if_binary',
    sparse_output=False
)
onehot=encoder.fit_transform(data)
print()
print(onehot)

[['blue']
 ['green']
 ['red']]

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [27]:
# Imputing missing numeric values with most_frequent strategy

import pandas as pd
import numpy as np
from sklearn.impute import SimpleImputer

students=[
    [85,'M','verygood'],
    [95,'F','excellent'],
    [60,None,'good'],
    [None,'M','average'],
    [70,'M','good'],
    [None,None,'verygood'],
    [60,'F','verygood'],
    [98,'M','excellent']
]

cols=['marks','gender','result']
df=pd.DataFrame(students , columns=cols)

print(df)

impute=SimpleImputer(
    missing_values=np.NaN,
    strategy='most_frequent'
)

result=df['gender'].values.reshape(-1,1)

print()
print(result)

df['gender']=impute.fit_transform(result)

print()
print(df)

   marks gender     result
0   85.0      M   verygood
1   95.0      F  excellent
2   60.0   None       good
3    NaN      M    average
4   70.0      M       good
5    NaN   None   verygood
6   60.0      F   verygood
7   98.0      M  excellent


AttributeError: `np.NaN` was removed in the NumPy 2.0 release. Use `np.nan` instead.

In [28]:
import pandas as pd
import numpy as np
from sklearn.impute import SimpleImputer

students=[
    [85,'M','verygood'],
    [95,'F','excellent'],
    [60,None,'good'],
    [None,'M','average'],
    [70,'M','good'],
    [None,None,'verygood'],
    [60,'F','verygood'],
    [98,'M','excellent']
]

cols=['marks','gender','result']
df=pd.DataFrame(students , columns=cols)

print("Original DF:")
print(df)

# Create imputer
imputer = SimpleImputer(missing_values=np.nan, strategy='most_frequent')

# Extract gender column (2D required for sklearn)
gender = df[['gender']]

print("\nGender Before Impute:")
print(gender.values)

# Fit & transform
df['gender'] = imputer.fit_transform(gender)

print("\nDF After Impute:")
print(df)


Original DF:
   marks gender     result
0   85.0      M   verygood
1   95.0      F  excellent
2   60.0   None       good
3    NaN      M    average
4   70.0      M       good
5    NaN   None   verygood
6   60.0      F   verygood
7   98.0      M  excellent

Gender Before Impute:
[['M']
 ['F']
 [None]
 ['M']
 ['M']
 [None]
 ['F']
 ['M']]


ValueError: 2

In [30]:
import pandas as pd
import numpy as np
from sklearn.impute import SimpleImputer

students=[
    [85,'M','verygood'],
    [95,'F','excellent'],
    [60,None,'good'],
    [None,'M','average'],
    [70,'M','good'],
    [None,None,'verygood'],
    [60,'F','verygood'],
    [98,'M','excellent']
]

cols=['marks','gender','result']
df=pd.DataFrame(students , columns=cols)

# Create imputer
imputer = SimpleImputer(missing_values=np.nan, strategy='most_frequent')

gender = df[['gender']]  # keep as 2D

# FIX: ravel() to convert 2D -> 1D
df['gender'] = imputer.fit_transform(gender).ravel()

print(df)


   marks gender     result
0   85.0      M   verygood
1   95.0      F  excellent
2   60.0   None       good
3    NaN      M    average
4   70.0      M       good
5    NaN   None   verygood
6   60.0      F   verygood
7   98.0      M  excellent


In [ ]:
s